### ISSUE TITLE
Support arm64 architecture

### ISSUE THREAD

**Issue by rkokkelk** [linuxserver/docker-foldingathome#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Support for arm64 architecture, which is supported by FoldingAtHome, see: 
* https://download.foldingathome.org/releases.py

```json
{
     { .. },
      {
        "oses": [
          "ARM Linux",
          "Raspberry Pi"
        ],
        "exts": "deb",
        "archs": "arm64 all",
        "files": [
          {
            "url": "https://download.foldingathome.org/releases/public/release/fahcontrol/debian-stable-64bit/v7.5/fahcontrol_7.5.1-1_all.deb",
            "filename": "fahcontrol_7.5.1-1_all.deb",
            "version": [
              7,
              5,
              1
            ],
            "project": "fahcontrol",
            "arch": "all",
            "ext": "deb"
          }
        ]
      }
    ],
    "platform": "lin64"
  }
}
```
Especially for homelabbers with Docker swarm running on Raspberry PIs, like me, it's a great addition to have FoldingAtHome running in the swarm.

## Current Behavior
| Digest         | OS/ARCH     | Compressed Size |
|--------------|-----------|------------|
| eebf2ffcdea2 | linux/amd64     | 45.09 MB        |

**Comment by mworthley** [comment]
I would also like to see this support. I have a few pi4s recently decommissioned from an upgrade and this feature would make the setup much more convenient.
