### ISSUE TITLE
GPU folding with AMD graphics card

### ISSUE THREAD

**Issue by scottsweb** [linuxserver/docker-foldingathome#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

AMD graphics card is not detected by container and I am unable to perform GPU folding. 

------------------------------

## Expected Behavior

Folding@Home can perform both CPU and GPU tasks. It would be great if I could make use of my GPU when using this container. I notice there is documentation for NVIDIA cards but nothing for AMD and at the moment, my AMD card is not detected.

## Current Behavior

Out of the box this container did not detect my graphics card and it is not available to F@H for jobs. From what I can tell GPU folding requires OpenCL to configured and an upto date graphics driver.  

I attached to the container with `docker exec -it folding bash` and decided to look at what might be going wrong. I believe the container is missing some required software. The first tool is `clinfo` which reports on the status of OpenCL. I installed it and it reported:

```
number of platforms 0
```

I then installed the following packages: `apt-get install mesa-opencl-icd ocl-icd-opencl-dev`. This gave me the following output from `clinfo`:

```
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 19.2.8
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD RAVEN (DRM 3.33.0, 5.3.0-7648-generic, LLVM 9.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 19.2.8
  Driver Version                                  19.2.8
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Max compute units                               11
  Max clock frequency                             1250MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
---- cut
```

The graphics card is now visible to F@H but unfortunately something is still not right.

<img width="617" alt="Screenshot 2020-04-22 at 22 17 34" src="https://user-images.githubusercontent.com/411945/80030388-6b8e7a00-84e8-11ea-8db6-0066ed4b4072.png">

<img width="966" alt="Screenshot 2020-04-22 at 22 26 39" src="https://user-images.githubusercontent.com/411945/80030400-6fba9780-84e8-11ea-9a8e-402939bae51d.png">

Depite being available to the software it will not start jobs. The error reported it by F@H is:

```
ERROR:126: Bad platformId size.
```

Full log:

```
19:37:07:WU03:FS01:0x22:*********************** Log Started 2020-04-21T19:37:06Z ***********************
19:37:07:WU03:FS01:0x22:*************************** Core22 Folding@home Core ***************************
19:37:07:WU03:FS01:0x22:       Type: 0x22
19:37:07:WU03:FS01:0x22:       Core: Core22
19:37:07:WU03:FS01:0x22:    Website: https://foldingathome.org/
19:37:07:WU03:FS01:0x22:  Copyright: (c) 2009-2018 foldingathome.org
19:37:07:WU03:FS01:0x22:     Author: John Chodera <john.chodera@choderalab.org> and Rafal Wiewiora
19:37:07:WU03:FS01:0x22:             <rafal.wiewiora@choderalab.org>
19:37:07:WU03:FS01:0x22:       Args: -dir 03 -suffix 01 -version 706 -lifeline 718 -checkpoint 15
19:37:07:WU03:FS01:0x22:             -gpu-vendor amd -opencl-platform 0 -opencl-device 0 -gpu 0
19:37:07:WU03:FS01:0x22:     Config: <none>
19:37:07:WU03:FS01:0x22:************************************ Build *************************************
19:37:07:WU03:FS01:0x22:    Version: 0.0.2
19:37:07:WU03:FS01:0x22:       Date: Dec 6 2019
19:37:07:WU03:FS01:0x22:       Time: 21:20:17
19:37:07:WU03:FS01:0x22: Repository: Git
19:37:07:WU03:FS01:0x22:   Revision: f87d92b58abdf7e6bf2e173cfbc4dc3e837c7042
19:37:07:WU03:FS01:0x22:     Branch: core22
19:37:07:WU03:FS01:0x22:   Compiler: GNU 4.8.2 20140120 (Red Hat 4.8.2-15)
19:37:07:WU03:FS01:0x22:    Options: -std=gnu++98 -O3 -funroll-loops
19:37:07:WU03:FS01:0x22:   Platform: linux2 4.9.87-linuxkit-aufs
19:37:07:WU03:FS01:0x22:       Bits: 64
19:37:07:WU03:FS01:0x22:       Mode: Release
19:37:07:WU03:FS01:0x22:************************************ System ************************************
19:37:07:WU03:FS01:0x22:        CPU: AMD Ryzen 5 2400GE with Radeon Vega Graphics
19:37:07:WU03:FS01:0x22:     CPU ID: AuthenticAMD Family 23 Model 17 Stepping 0
19:37:07:WU03:FS01:0x22:       CPUs: 8
19:37:07:WU03:FS01:0x22:     Memory: 13.59GiB
19:37:07:WU03:FS01:0x22:Free Memory: 3.48GiB
19:37:07:WU03:FS01:0x22:    Threads: POSIX_THREADS
19:37:07:WU03:FS01:0x22: OS Version: 5.3
19:37:07:WU03:FS01:0x22:Has Battery: false
19:37:07:WU03:FS01:0x22: On Battery: false
19:37:07:WU03:FS01:0x22: UTC Offset: 2
19:37:07:WU03:FS01:0x22:        PID: 722
19:37:07:WU03:FS01:0x22:        CWD: /config/work
19:37:07:WU03:FS01:0x22:         OS: Linux 5.3.0-7648-generic x86_64
19:37:07:WU03:FS01:0x22:    OS Arch: AMD64
19:37:07:WU03:FS01:0x22:********************************************************************************
19:37:07:WU03:FS01:0x22:Project: 11762 (Run 0, Clone 9867, Gen 12)
19:37:07:WU03:FS01:0x22:Unit: 0x0000002280fccb0a5e7113ba6f96ab4d
19:37:07:WU03:FS01:0x22:Reading tar file core.xml
19:37:07:WU03:FS01:0x22:Reading tar file integrator.xml
19:37:07:WU03:FS01:0x22:Reading tar file state.xml
19:37:07:WU03:FS01:0x22:Reading tar file system.xml
19:37:07:WU03:FS01:0x22:Digital signatures verified
19:37:07:WU03:FS01:0x22:Folding@home GPU Core22 Folding@home Core
19:37:07:WU03:FS01:0x22:Version 0.0.2
19:37:07:WU03:FS01:0x22:ERROR:126: Bad platformId size.
19:37:07:WU03:FS01:0x22:Saving result file ../logfile_01.txt
19:37:07:WU03:FS01:0x22:Saving result file science.log
19:37:07:WU03:FS01:0x22:Folding@home Core Shutdown: BAD_WORK_UNIT
```

## Steps to Reproduce

1. Install the container on an AMD Ryzen 5 with integrated graphics (Vega)
2. Note that folding@home does not detect the graphics card

## Environment
**OS:**  Ubuntu/POP_OS! 19.10 5.3.0-7648-generic
**CPU architecture:** x86_64   
**How docker service was installed:**      

Docker version 19.03.6, build 369ce74a3c via apt-get
## Command used to create docker container (run/create/compose/screenshot)

Docker compose:

```
services:
    foldingathome:
        image: linuxserver/foldingathome
        volumes:
            - "/media/user/Media/Containers/folding/data:/config"
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Europe/Stockholm
        ports:
            - 7396:7396
            - 36330:36330
        devices:
           - /dev/dri:/dev/dri
        restart: unless-stopped
        container_name: folding
```

The devices section was added as I believe this may provide GPU access from the host to the container, but I haven't been able to verify this yet.

## Docker logs

See above

**Comment by tobbenb** [comment]
Google says that the error you get is usually fixed by installing the correct driver, so it looks like it's something to do with the driver.
Have you checked the permissions on /dev/dri and it's content in both the container and the host?

None of us have any AMD CPUs with gpu, at least not available for testing, so we can't test it.

**Comment by scottsweb** [comment]
Thank you for the pointers, after a bit more tinkering I have managed to get it to work.

Additional packages installed:

```
clinfo 
xz-utils 
pciutils 
ocl-icd-opencl-dev
```

I then manually installed OpenCL/AMD packages from the AMD Driver download page:

```
curl -L -O --referer http://support.amd.com  https://drivers.amd.com/drivers/linux/amdgpu-pro-18.40-697810-ubuntu-18.04.tar.xz

tar xvf amdgpu-pro-18.40-697810-ubuntu-18.04.tar.xz 

cd amdgpu-pro-18.40-697810-ubuntu-18.04

./amdgpu-pro-install --opencl=legacy,pal --headless
```

I did get a couple of tiny errors during the install and had to run `apt --fix-broken install` to get back on track. 

Having the device in the `docker-compose.yaml` seemed to be a requirement too.

I am now folding on my GPU! 

I am not sure if any of these modifcations would be useful in your container, but happy to close either way.

**Comment by aptalca** [comment]
Thanks, let's leave this open for now. We'll use this info as the starting point for our testing (once we get a dev environment set up)

**Comment by e3b0c442** [comment]
I followed the steps above for Ubuntu 20.04 and still get the message `No CUDA or OpenCL 1.2+ support detected for GPU`. Has anyone else had luck here?

**Comment by scottsweb** [comment]
The drivers have been updated on the AMD site, so you now need to use:

```
https://drivers.amd.com/drivers/linux/amdgpu-pro-20.40-1147287-ubuntu-18.04.tar.xz
```

It looks like it is close to working for me, but I am currently stuck on `Configuring platform OpenCL`.

**Comment by lbibass** [comment]
> The drivers have been updated on the AMD site, so you now need to use:
> 
> ```
> https://drivers.amd.com/drivers/linux/amdgpu-pro-20.40-1147287-ubuntu-18.04.tar.xz
> ```
> 
> It looks like it is close to working for me, but I am currently stuck on `Configuring platform OpenCL`.

I am also having the same issue. Stuck on Configuring Platform OpenCL.

**Comment by scottsweb** [comment]
I have a feeling it might be getting stuck due to a kernel mismatch between the container and the OS. I am running a Ubuntu derivative on the latest release (20.10) and the drivers from AMD are expecting something based on an older kernel for 20.04. I think that mismatch between container, drivers and host are causing them to not install properly. I will let you know if I figure it out.

**Comment by stratege1401** [comment]
Hello,

if needed, i have a sitting ryzen3 2200G sitting on a shelve. You just miss a mobo compatible ...
Will be happy to participate by donating this piece of hardware to your team.

**Comment by stratege1401** [comment]
sorry, had to withdraw my cpu offert....

**Comment by jmpolom** [comment]
The issue here is that for using OpenCL in a container with AMD GPUs requires that the container image be built with the [proprietary AMD driver](https://repo.radeon.com/amdgpu-install/21.40.2/ubuntu/bionic/amdgpu-install_21.40.2.40502-1_all.deb) included. This proprietary driver includes the secret sauce to make OpenCL work on the Radeon platforms.

Looking at the Dockerfile in the repo for this image, it does not include the proprietary portion of the amdgpu driver. The observed behavior above would be expected.

I really like using folding@home for doing loaded burn in tests on systems but don't like having to install it. Perhaps I will get around to adding the proprietary AMD driver to this container image and sending a PR.

**Comment by NevesLucas** [comment]
Has there been any progress on this? also trying to use this container on my radeon card. I think the dependency would be through rocm nowadays: https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.3/page/How_to_Install_ROCm.html
with the `opencl` usecase

**Comment by aptalca** [comment]
Look into how the amd drivers are installed in this mod: https://github.com/linuxserver/docker-mods/tree/jellyfin-amd
