### ISSUE TITLE
GPU slot issue with 7.6.21-ls26

### ISSUE THREAD

**Issue by Gnomuz** [linuxserver/docker-foldingathome#7]
Hi,
I've been folding with this container for months under Unraid. My current setup is Unraid 6.9.0-rc35 + Nvidia driver plugin, Nvidia drivers 455.45.01 with a Quadro P2000 GPU. The container has been automatically updated from 7.6.21-ls25 to 7.6.21-ls26 during the night.
Since the restart, the GPU slot is disabled with the following message in the log :
" 08:22:15:WARNING:FS01:No CUDA or OpenCL 1.2+ support detected for GPU slot 01: gpu:43:0 GP106GL [Quadro P2000] [MED-XN71]  3935.  Disabling."
The setup is exactly the same as yesterday evening. I tried to delete the GPU slot with FAHControl and restart. The GPU is recognized, the slot is recreated but still the same message.
As a workaround before a fix, docker newbie question : how could I pull the previous release (7.6.21-ls25) of the container which worked just fine ?
Thanks in advance for the support.

**Comment by Gnomuz** [comment]
I got support on discord, and downgraded to ls25 (adding ":7.6.21-ls25" to the repository in the template). The issue was I have v455.45.01 Nvidia drivers in Unraid, and ls26 no longer supports this version. As I can't upgrade the drivers easily, I'll stick to ls25 for the moment.

**Comment by aptalca** [comment]
@Gnomuz 
Will you be able to test a dev build for us?

**Comment by Gnomuz** [comment]
No problem, I'll have access to my server in 1 hour.

**Comment by Gnomuz** [comment]
I DM you in Discord when I'm in front of the server. Shopping with my gf
for the moment :-(
Fyi I'm in France and it's 6:30 pm .
Let me know if it's ok for you.

**Comment by aptalca** [comment]
Thanks, no rush. I just wanted to see if you were up for testing. I still had to commit and push and all that.

Anyway, the build is ready.

Can you use the following as the image and try nvidia?
`lsiodev/foldingathome:7.6.21-pkg-9b81d293-dev-a89f42ebd8faa4e6122a851684d2a9756f239db8`
Just replace `linuxserver/foldingathome` with the above and see if it works.

Thanks

**Comment by Gnomuz** [comment]
Hi,
I've just tested your dev build above, and everything is working fine for me. The GPU slot was initialized properly, and a new WU is being folded (5% by now) with the usual performance for the Quadro P2000 on this rig (circa 540k PPD).
Just a question, if I upgrade the host drivers to the latest version v460.32.03 from currently installed v455.45.01, may it raise an issue ?
Thanks for your help, and do not hesitate if you ever need a tester under Unraid !

**Comment by tobbenb** [comment]
It shouldn't be an issue updating the unraid Nvidia drivers. 
We removed the package that installed some drivers that is already passed through to the container using the Nvidia runtime and added another file that is needed for it to work.
